* Inbox
** FPS = F / T
60 = 1 / T, so T equals 16 ms
30 = 1 / T, so T equals 33 ms
[2026-08-19 Wed 10:41]
** For normalization for vectors to 1.0

#+BEGIN_SRC C
Vector3f normalizeFloat3(Vector3f vector) {
  float length = sqrtf(vector.x*vector.x + vector.y*vector.y + vector.z*vector.z);

  vector.x = vector.x / length;
  vector.y = vector.y / length;
  vector.z = vector.z / length;

  return vector;
}
#+END_SRC

[2026-08-27 Thu 08:59]
[[file:c:/dev/cielo/cielo/code/terrain_demo1.cpp::Matrix4f projection;]]
** Vector lengths use the Pythagorean algorithm a2 + b2 = c2

#+BEGIN_SRC C
float
vec2_length(vec2_t v)
{
  return sqrt((v.x * v.x) + (v.y * v.y));
}

float
vec3_length(vec3_t v)
{
  return sqrt((v.x * v.x) + (v.y * v.y) + (v.z * v.z));
}
#+END_SRC
[2026-09-11 Fri 18:46]
[[file:c:/dev/3drenderer/src/vector.c::float]]

* Slope
Slope of X - the changing Y given that X is going to increment by 1
m = (y2 - y1) / (x2 - x1);

* Inverse Slope
Slope of Y - the changing X given that Y is going to increment by 1
m = (x2 - x1) / (y2 - y1);

* Vector Cross Product - outputs a perpendicular vector
This brings the perpendicular output

X  = _VecA - VecB_
Nx =  AyBz - AzBy
Ny =  AzBx - AxBz
Nz =  AxBy - AyBx

Magnitude of the Cross Product || a x b || = || a || || b || sin0

*The face where the vertices were created CCW will be where the normal faces*
*If the face has its vertices created CW then the normal faces away*
*Whereas if the has has its vertices created CCW then the normal faces in*

Normals are only for Vector 3D
Triangle points ABC
(B - A) x (C - A) = Normal (Perpendicular Vector) 90 degree angle from triangle face

* Vector Dot Product - outputs a scalar float, tests how /aligned/ the two vectors are
Projects VecB onto VecA 

If both vectors are perfectly aligned (laying on top of each other) then dot product is 1.0
If vectors are 90 degree from each other then dot product is 0.0 (Perpendicular) _no projection_
If vectors are more than 90 degrees then dot product become - and if completely opposite then -1.0
These are only true if both vectors are unit vectors where each value is 1.0

2D
A x B = AxBx + AyBy

3D
A x B x C = AxBxCx + AyByCy

* Culling Algorithm

1. Find vectors B-A and C-A
2. Take their Cross Product to get the Perpendicular Normal N
3. Find the Camera Ray vector by subtracing the camera position from point A
4. Take the Dot Product between the normal N and the Camera Ray

Render if Dot Product is greater than 0.0 and do NOT Render if Dot Product is less than 0.0
* Normalize Normal - gets the vector to 1.0
v = v / || v ||
#+BEGIN_SRC C
void
vec3_normalize(vec3_t* v)
{
  float length = (v->x * v->x) + (v->y * v->y) + (v->z * v->z);

  v->x /= length;
  v->y /= length;
  v->z /= length;
}
#+END_SRC

* Similar triangles - share ratio
a / b = c / d
           (x0,y0)
             |\
             | \
        c    |  \
             |   \
d  (x1,y1)   |____\(Mx,My)
             |  a  \
             |      \
             |       \
             |        \
             |_________\(x2,y2)
                  b

Mx - x0 / x2 - x0 = y1 - y0 / y2 - y0

a   c
_ = _
b   d

(Mx-x0)(y2-y0) = (x2-x0)(y1-y0)

Mx - x0 = (x2-x0)(y1-y0) / (y2-y0)

*Mx = (x2-x0)(y1-y0) / (y2-y0) + x0*
* Painter's Algorithm - sort triangles by face's avg_depth
Each triangle has 3 vertices so

avg_depth = (v1.z + v2.z + v3.z) / 3

Then sort the triangles based on their depth so you can have the triangles that are farthest be drawn first
* Sorting Algorithms

|-----------+----------------------+--------------+------------------+-------------|
| Algorithm | Comparisons          | Swaps (best) | Swaps (worst)    | Early exit? |
|-----------+----------------------+--------------+------------------+-------------|
| bubble    | O(n²) worst case     | O(n)         | O(n²) worst case | Yes         |
| selection | Always exactly O(n²) | O(n²)        | O(n²) worst case | No          |
|-----------+----------------------+--------------+------------------+-------------|

Radix sort
Merge sort
Quick sort
** Selection sort
#+begin_src C
// Sort the triangles to render by their avg_depth
    int num_triangles = array_length(triangles_to_render);
    for (int i = 0; i < num_triangles; i++) {
        for (int j = i; j < num_triangles; j++) {
            if (triangles_to_render[i].avg_depth < triangles_to_render[j].avg_depth) {
                // Swap the triangles positions in the array
                triangle_t temp = triangles_to_render[i];
                triangles_to_render[i] = triangles_to_render[j];
                triangles_to_render[j] = temp;
            }
        }
    }
#+end_src

** Bubble sort
#+BEGIN_SRC C
  int changes = 0;
  int len = array_length(triangles_to_render);
  if (!triangles_to_render) abort();
  do
  {
    changes = 0;
    for (int i = 0; i < len - 1; i++)
    {
      if (triangles_to_render[i].avg_depth < triangles_to_render[i + 1].avg_depth)
      {
        tri_swap(&triangles_to_render[i], &triangles_to_render[i + 1]);
        changes++;
      }
    }
    
  } while (changes != 0);
#+END_SRC
* Matrices
** Add/Subtract

| 2 3 | + | 4 2 |
| 1 8 |   | 1 3 |

| 6 5  |
| 2 11 |

| 2 3 | - | 4 2 |
| 1 8 |   | 1 3 |

| -2 1 |
|  0 5  |

** Matrix Multiplication just like the Dot Product

| 1 2 | x | 5 6 |
| 3 4 |   | 7 8 |

| (1*5) + (2*7) (1*6) + (2*8) |
| (3*5) + (4+7) (3*6) + (4*8) |

| 19 22 |
| 43 50 |

_Rules_ 
N x M = M x P  
/Can only do multiply matrix when number columns of the left matrix is equal to the number of rows of the right matrix/

Result will have the number of rows of the 1st number of columns of the 2nd N x P

A * B != B * A
Matrix Multiplication is not commutative

| 1 2 -1 | x | 3  1 |
| 2 0  1 |   | 0 -1 |
             | -2 3 |

| (1*3) + (2*0) + (-1*-2) (1*1) + (2*-1) + (-1*3) |
| (2*3) + (0*0) + (1*-2)  (2*1) + (0*-1) + (1*3)  |

| 5  -4 |
| 4   5 |

| 44.5  65.3  -23.0   | x | 4  0  3  | (Cannot 3x3 multiplied by 2x3 *not* happening) |
|  6.0   6.0    2.44  |   | 3 4.5 2 |                                                |
| -3.4  -3.4   35.66  |   |         |                                                |

/Can only do multiply matrix when number columns of the left matrix is equal to the number of rows of the right matrix/

** Identity Matrix - a square matrix with 1s on the diagonal and 0s everywhere else

| 1 0 0 0 |
| 0 1 0 0 |
| 0 0 1 0 |
| 0 0 0 1 |

if you multiply a matrix with identity matrix the diagonal keep the original values and the 0s
make sure that none of the original values are changed

any matrix multiplied by an identity matrix will have the original values of that matrix unchanged

aka Unit matrix or Matrix eye
** Rotation Matrix - linear transformation

$X'$ = xcosA - ysinA
$Y'$ = xsinA + ycosA

#+begin_src C
vec3_t
vec3_rotate_z(vec3_t v, float angle)
{
    vec3_t rotated_vector = {
        .x = v.x * cos(angle) - v.y * sin(angle),
        .y = v.x * sin(angle) + v.y * cos(angle),
        .z = v.z
    };
    return(rotated_vector);
}
#+end_src

| $x'$ | = | cosA -sinA | * | x | = | xcosA - ysinA |
| $y'$ |   | sinA  cosA |   | y |   | xsinA + ycosA |
** Transformation Matrices - linear transformations
mat4_t which is a 4x4 matrix

4th column in mat4_t does Translation

| m m m m |   | x |
| m m m m | * | y |
| m m m m |   | z |
| m m m m |   | w | 

Cannot do 4x4 and 3x1 so we add w
w will be 1

4x4 Matrices used for Scaling, Translation, and Rotation

/Order is very important when doing Matrix Multiplication/

1. Scale
2. Rotation
3. Translation

Translation changes the center of reference so it needs to be done LAST!! It changes the origin
while Scale and Rotation do not

*** Scale Matrix - Linear origin does not change

| sx 0  0  0 |   | x |
| 0  sy 0  0 | * | y |
| 0  0  sz 0 |   | z |
| 0  0  0  1 |   | 1 |

| (sx*x) + 0 + 0 + 0 |
| 0 + (sy*y) + 0 + 0 |
| 0 + 0 + (sz*z) + 0 |
| 0 + 0 + 0 +  (1*1) |


|sx*x|
|sy*y|
|sz*z|
|  1 |

#+begin_src C
mat4_t mat4_make_scale(float sx, float sy, float sz)
{
    // | sx 0 0 0 |
    // | 0 sy 0 0 |
    // | 0 0 sz 0 |
    // | 0 0 0 1  |
    mat4_t m = mat4_identity();
    m.m[0][0] = sx;
    m.m[1][1] = sy;
    m.m[2][2] = sz;
    return m;
}
#+end_src
*** Translation Matrix - Not Linear origin does change
| 1 0 0 tx |   | x |
| 0 1 0 ty | * | y |
| 0 0 1 tz |   | z |
| 0 0 0 1  |   | 1 |


| x + 0 + 0 + tx |
| 0 + y + 0 + ty |
| 0 + 0 + z + tz |
| 0 + 0 + 0 + 1  |

| x + tx |
| y + ty |
| z + tz |
|   1    |

#+begin_src C
mat4_t mat4_make_translation(float tx, float ty, float tz)
{
    // | 1 0 0 tx |
    // | 0 1 0 ty |
    // | 0 0 1 tz |
    // | 0 0 0 1  |

    mat4_t m = mat4_identity();
    m.m[0][3] = tx;
    m.m[1][3] = ty;
    m.m[2][3] = tz;

    return m;
}
#+end_src
*** Rotation Matrix - Linear origin does not change

2D Rotation Matrix

|$x'$| = |cosA - sinA| * |x|
|$y'$| = |sinA   cosA|   |y|

3D Rotation Matrix

Rotate in Z

| cosA -sinA  0  0 |   | x |
| sinA  cosA  0  0 | * | y |
| 0     0     1  0 |   | z |
| 0     0     0  1 |   | 1 |

/While X and Y change Z remains unchanged/

// NOTE(trist007): x and y change while z remains unchanged
#+begin_src C
mat4_t mat4_make_rotation_z(float angle)
{
    float c = cos(angle);
    float s = sin(angle);

    // c -s 0 0
    // s  c 0 0
    // 0  0 1 0
    // 0  0 0 1

    mat4_t m = mat4_identity();
    m.m[0][0] = c;
    m.m[0][1] = -s;
    m.m[1][0] = s;
    m.m[1][1] = c;

    return m;
}
#+end_src

Rotate in X

| 1     0   0     0 |   | x |
| 0  cosA  -sinA  0 | * | y |
| 0  sinA   cosA  0 |   | z |
| 0     0     0   1 |   | 1 |

// NOTE(trist007): first row and column unchanged cause X remains unchanged

#+begin_src C
mat4_t mat4_make_rotation_x(float angle)
{
    float c = cos(angle);
    float s = sin(angle);

    // 1  0  0  0
    // 0  c -s  0
    // 0  s  c  0
    // 0  0  0  1

    mat4_t m = mat4_identity();
    m.m[1][1] = c;
    m.m[1][2] = -s;
    m.m[2][1] = s;
    m.m[2][2] = c;

    return m;
}
#+end_src


Rotate in Y

| cosA   0    sinA    0  |   | x |
| 0      1     0      0  | * | y |
| -sinA  0     cosA   0  |   | z |
| 0      0     0      1  |   | 1 |

// NOTE(trist007): y column stays the same 0 1 0 0
 #+begin_src C
mat4_t mat4_make_rotation_y(float angle)
{
    float c = cos(angle);
    float s = sin(angle);

    //  c  0  s  0
    //  0  1  0  0
    // -s  0  c  0
    //  0  0  0  1

    mat4_t m = mat4_identity();
    m.m[0][0] = c;
    m.m[0][2] = s;
    m.m[2][0] = -s;
    m.m[2][2] = c;

    return m;
}
#+end_src

The above is for right-handed coordinate system

For a left-handed coordinate system, the rotation matrices are the same structure as right-handed ones, but the sign of the sine terms flips relative to the RHS convention — because "positive rotation" in LHS goes clockwise when looking down the positive axis (versus counterclockwise in RHS).

So left-handed coordinate system Rotation Matrices would look like this

Rotate around X:

| 1      0        0      |
| 0    cos(θ)   sin(θ)   |
| 0   -sin(θ)   cos(θ)   |

Rotate around Y:

| cos(θ)   0   -sin(θ) |
|   0      1     0     |
| sin(θ)   0    cos(θ) |

Rotate around Z:

| cos(θ)   sin(θ)   0 |
| -sin(θ)  cos(θ)   0 |
|   0        0      1 |
*** World Matrix
                                                       | x |
Translation Matrix * Rotation Matrix * Scale Matrix *  | y |   = World Matrix
                                                       | z |
                                                       | 1 |

So then you can just multiply once using the World Matrix to get the final Transform

World Matrix            | x |
                *       | y |
                        | z |
                        | 1 |

The world matrix is the combination / multiplication of all the matrices that transform the original
vectors and place the overall 3D Mesh in its correct place in the world/scene

Shear is another Transformation it does not change origin so it is a Linear Transformation
** Projection Matrix
Goals for a Projection Matrix
1. Aspect ratio: adjust x and y values based on the screen width and height
2. Field of view: adjust x and y values based on the FOV angle 
3. Normalization: adjust x, y, and z values to sit between -1 and 1
4. Preserve original Z: save the original, unnormalized z (depth) somewhere after the projection
   
*** Orthographic - all objects appear the same size no matter the z value
*** Perspective - objects with a z value closer to the screen will appear closer to the screen

                                    | x |
Perspective projection matrix 4x4 * | y |  -> Perspective divide 1/z -> Depth Normalization (NDC)  -> Screen Space
                                    | z |                               Normalized Device Coordinates 
                                    | 1 |
OpenGL: -1 to 1
D3D11:   0 to 1
Vulkan:  0 to 1

Ready to be rasterized after Depth Normaliztion to Screen Space

Aspect Ratio

horizontal - a = w / h
vertical   - a = h / w  (reciprocal)

                                         Reciprocal (less than 1 since heights are all shorter than the width)
     320                      
240  4:3  -> a = 320 / 240 = 1.333       a = 240 / 320  = 0.75

     1280
800  16:10 -> a = 1280 / 800 = 1.6       a = 800 / 1280 = 0.625

     1600
900  16:9  -> a = 1600 / 900 = 1.777     a = 900 / 1600 = 0.562

Transformation for Aspect Ratio Scaling Factor make width smaller so as screen gets wider a cube still looks like 1x1x1

| x |    | ax |
| y | -> | y  |
| z |    | z  |

-1.                            +1
------------------------------
\             |             /
 \            |            /
  \           |           /
   \          |          /
    \         |         /
     \        |        /
      \       |       /
       \      |      /
        \     |     /
         \    |    /
          \   |   /
           \  |  /
            \ | /
             \|/
              
             FOV
             
SohCahToa

a = h / w
f = 1 / tan(0/2)  // Scaling Factor

Transformation

| x |    | afx |
| y | -> | fy  | -> Perspective divide x/z y/z z/z = NDC
| z |    |  z  |
*** zFar and zNear

zNear 0 and zFar 1 - normalized

Transformation

| x |    | afx     |
| y | -> | fy      |
| z |    | LambdaZ |


Aspect Ratio: a = h /w

Field of View: f = t / tan(0/2)

lambdaS = scaling factor
lambdaT = translation factor (offset)

Perspective Projection Matrix (lambdaS and lambdaT are below)

| (h/w) (1/tan(0/2))        0	     0         0       |   | X |   | Xp |      Xp / z         |
| 0                    (1/tan(0/2))    0         0       | * | Y | = | Yp | ->   Yp / z  =  NDC |
| 0                         0      lambdaS       lambdaT |   | Z |   | Zp |      Zp / z         |
| 0                         0          1         0       |   | 1 |   | Wp |                     |
                                       ^saving original unnormalized Z value in the Wp component

Z Normalization is the 3rd row of ?s for the NDC phase                                  

anything closer than zNear does not get rendered
anything farther than the zFar does not get rendered
                                       
             zFar
------------------------------
\             |             /
 \            |            /
  \           |           /
   \          |          /
    \         |         /
     \        |        /
      \       |       /
       \      |      /
        \     |     /
         \---------/  zNear   -
          \   |   /            |
           \  |  /             |   zNear offset/translation
            \ | /              |
             \|/               |
                              -
             FOV
 
Translation = LambdaS*Z + LambdaT = Zp
              scale(*) + offset(+)
              

After the perspective divide, we want a function f(z) such that: f(zNear) = 0 and f(zFar) = 1

f(z) = lambdaS*Z + lambdaT / z

lambdaS*Z = scaling factor * Z
lambdaT = translation offset

When z = zNear, f(z) = 0

lambdaS*zNear + lambdaT / zNear = 0

_lambdaT = - lambdaS*zNear_

When z = zFar, f(z) = 1

lambdaS*Z + lambdaT / zFar = 1

_lambdaS*zFar + lambdaT = zFar_

lambdaS*zFar - lambdaS*zNear = zFar

lambdaS(zFar - zNear) = zFar

_lambdaS = zFar / (zFar - zNear)_

lambdaT = - (zFar / zFar - zNear)*zNear

_lambdaT = -zFar * zNear / zFar - zNear_

Perspective Divide becomes 

Xp / Wp
Yp / Wp
Zp / Wp

since Z = Wp(old z value)

*At this point we now have NDC everything normalized between 0 and 1*

Normalized Device Coordinates (NDC) aka Image Space where everything is ready to be rasterized to the screen

#+begin_src C
mat4_t mat4_make_perspective(float fov, float aspect, float znear, float zfar)
{
    // | (h/w)*1/tan(fov/2)           0                    0             0 |
    // | 0                            1/tan(fov/2)         0             0 |
    // | 0                            0             zf/(zf-zn)     (-zf*zn)/(zf-zn)  |
    // | 0                            0                    1             0 |

    mat4_t m = {{{ 0 }}};
    m.m[0][0] = aspect * (1 / tan(fov / 2));
    m.m[1][1] = 1 / tan(fov / 2);
    m.m[2][2] = zfar / (zfar - znear);
    m.m[2][3] = (-zfar * znear) / (zfar - znear);
    m.m[3][2] = 1.0;

    return m;
}

vec4_t mat4_mul_vec4_project(mat4_t mat_proj, vec4_t v)
{
  // multiply the projection matrix by our original vector
  vec4_t result = mat4_mul_vec4(mat_proj, v);

  // perform perspective divide with original z-value that is now stored in w
  if (result.w != 0.0)
  {
    result.x /= result.w;
    result.y /= result.w;
    result.z /= result.w;
  }
  return result;
}
#+end_src

The Z Remapping is Not Linear

We just saw that we use our perspective projection matrix to normalize the depth values between 0 and 1.

Most people usually expect the normalized depth to be evenly distributed across [0, 1], but it is not. Because of the /z perspective divide, the mapping is hyperbolic. This means precision is concentrated near znear and gets coarser as you approach zfar.

Let's look at an example. Let's say that we have 50 different points and we want to project them. The first point z coordinate starts at 10.0, and each new point's depth increases by 5 units.



If we plot the depth of these original 3D points, we get evenly-spaced z values for all 50 vertices.



Now, if we proceed to multiply our vertices by the projection matrix and perform the perspective divide, we should have all our points normalized (in NDC).



If we plot the normalized z values of our projected NDC vertices, we get a non-linear distribution.



This non-linearity is an inherent property of the perspective projection, and it is also why choosing a znear that is too small (e.g. 0.001) is dangerous, as it compresses almost all your depth precision into a tiny region near the camera, causing z-fighting on distant geometry.

Z-fighting is a visual glitch in 3D computer graphics where two overlapping surfaces rapidly flicker, blend, or tear because they share the "same" distance from the camera. In our case, the values are not the same in theory, but the lack of numerical precision results in adjacent samples receiving identical depth values after projection onto the screen, despite having distinct z-coordinates in world space.



The issue of z-fighting is not really a problem for us right now, but I just wanted everyone to leave this lecture knowing that the normalization of our depth values is not linear.


Example of flicker caused by z-fighting

We might also experience z-fighting when the [znear:zfar] range is excessively large, which is why many programmers suggest keeping this interval as tight as possible to mitigate depth precision issues.

This non-linear nature of the normalized depth values might also helps us understand how we achieve the correct remapping in the first place. Remember how we used one multiplication (scaling term) and one subtraction (translation term) to map our depth coordinate to [0:1]?



Imagine the depth values as a rubber ruler. Let’s say that, initially, our depth extends from 0.1 to 100.



As we know, the projection does not stretch this ruler uniformly. Instead, it compresses it much more as you move farther away (because objects far away don't need as much precision for visibility testing).

The translation term is the one creating this varying compression, through the later division by z.



And the scaling term then shifts the whole curve, so that the compressed near endpoint lands exactly at 0, and the compressed far endpoint lands exactly at 1.



These z entries of the projection matrix work together to shape our depth curve. The translation term creates the non-linear distribution that concentrates precision near the viewer, while the scaling term offsets that curve so it passes exactly through the desired endpoints (0 at the near plane and 1 at the far plane).

Wait a minute! “Gustavo, are you telling me that the λs entry from our matrix is the one actually responsible for offsetting the depth values, and the λt is the one actually scaling them?”

That’s right! And the reason for that is because we must remember that we always divide the projected values by z in the perspective divide stage. This division effectively cancels out the z's from the first term and leaves us with a 1/z (hyperbolic) in the second one.



Therefore, after the perspective divide, we end up with a constant term (that shifts/offsets the values after the divide) and a 1/z term (that scales/compresses our values after the divide).

I know a lot of great graphics programmers that either never understood this normalization process, or still get very confused about how the normalization happens. I hope these past few lectures helped you create some good intuition on how this depth normalization is really achieved.

And before we continue, I just want to also mention that this idea of creating a projection matrix is something very common in popular modern graphics APIs, like OpenGL and Direct3D.

For example, Direct3D has a function called D3DXMatrixPerspectiveFovLH() that receives as parameters the field of view, the aspect ratio, and the values of znear and zfar. You can read about this function in Microsoft’s DirectX official documentation here. As you probably noticed, this function is very similar to our mat4_make_perspective().

OpenGL also has a function to create its perspective projection matrix. The function is called glFrustum() and this function behaves a bit different than ours since OpenGL's idea of a perspective projection matrix contains some different assumptions about how znear and zfar works and also accounting for OpenGL's right-handed coordinate system. Remember how we spoke that OpenGL normalizes the depth values to sit inside the interval [-1,+1] instead of [0,1]?

As far as the programmer is concerned, these Direct3D and OpenGL functions can be used as black boxes. You can simply pass the correct parameters and the graphics API will handle all the internals of the projection matrix for you. That being said, it is super important that we understand that the projection matrix that we are using is different than these projection matrices used by old fixed-function OpenGL or Direct3D. It's important to mention this because some online resources that you'll find out there will explain how to derive OpenGL's perspective projection matrix and they will end up with different formulas and different matrix entries than what we used. Every graphics API can use a different approach and these different assumptions have a direct impact on how we populate the entries of our projection matrix.

Still, it feels good to know how the matrix sausage is made. 🙂
*** Row Major vs Column Major

Column Major is |x| Post Multiply
                |y|
                |z|
                |w|

Row Major is 
[x y z w] Pre Multiply

Number of Columns on the Left matrix had to be equal to the Number of Rows on the Right matrix in
order to do Matrix Multiplication

| OpenGL  | column major |
| Vulkan  | column major |
| Blender | column major |
| D3D11   | row major    |

Column Major
     m          v
| m m m m |   | x |   |$x'$|
| m m m m | * | y | = |$y'$| Post Multiply vector is on right
| m m m m |   | z |   |$z'$|
| m m m m |   | w |   |$w'$|
  4x4          4x1     4x1

Row Major
     v            m
              [ m m m m ]
[ x y z w ] * [ m m m m ] Pre Multiply vector is on left
              [ m m m m ]  = [ $x'$ $y'$ $z'$ $w'$ ]
              [ m m m m ]
   1x4            4x4

Order of Multiplication for Row-major & Column-Major

Order of Matrix Multiplication for Row-major & Column-major

Transformations applied to a point or a vector using row-major can be written in sequential order (or reading order). Imagine for instance that you want to first rotate point P around the y-axis, then rotate P again around the z-axis, and finally translate point P using matrix T. In a row-major order we can write:

P' = P * Ry * Rz * T

Now, when using a column-major notation (the one I use in the slides of the course), we would need to call the transforms in the reverse order (which some people find counter-intuitive):

P' = T * Rz * Ry * P

Some people may think there must be a reason to prefer one system to another. Both conventions are correct and give us the same result, but for technical reasons, most mathematics and physics books generally treat vectors as column vectors.

Order of transformation when we use column-major matrices is more similar in mathematics to the way we write function evaluation and composition.

As a summary, if we want to:

First Rotate around the y-axis
Then Rotate around the z-axis
Then Translate using matrix T
We will have to perform the following order of multiplications:

In row-major: P' = P * Ry * Rz * T
In column-major: P' = T * Rz * Ry * P
